FROM node:14

ARG BUNDLE_DIR

RUN apt-get update && apt-get install -y ca-certificates

# This is a template Dockerfile for the bundle's invocation image
# You can customize it to use different base images, install tools and copy configuration files.
#
# Porter will use it as a template and append lines to it for the mixins
# and to set the CMD appropriately for the CNAB specification.
#
# Add the following line to porter.yaml to instruct Porter to use this template
# dockerfile: Dockerfile.tmpl

# You can control where the mixin's Dockerfile lines are inserted into this file by moving "# PORTER_MIXINS" line
# another location in this file. If you remove that line, the mixins generated content is appended to this file.
# PORTER_MIXINS

# Use the BUNDLE_DIR build argument to copy files into the bundle
COPY . $BUNDLE_DIR
RUN chmod +x $BUNDLE_DIR/db_migration.sh
RUN chmod +x $BUNDLE_DIR/zip_deploy.sh
RUN chmod +x $BUNDLE_DIR/utils.sh
RUN /bin/bash -c "az extension add --yes --source https://k8seazurecliextensiondev.blob.core.windows.net/azure-cli-extension/appservice_kube-0.1.8-py2.py3-none-any.whl"
